import type { CSSProperties } from "react";

/** Shared styles across the Skill detail tabs. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", marginBottom: 20 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  enabledLabel: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  filenameBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    borderRadius: "6px 6px 0 0",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 10, marginTop: 10 } satisfies CSSProperties,
  savedNote: { alignSelf: "center", fontSize: 13, color: "var(--ok)" } satisfies CSSProperties,
  previewBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 24,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  statsRow: { display: "flex", gap: 16, marginBottom: 24 } satisfies CSSProperties,
  stat: {
    flex: 1,
    padding: "16px 18px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  statLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  statVal: { fontSize: 22, fontWeight: 700 } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    padding: "10px 14px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    marginBottom: 6,
  } satisfies CSSProperties,
  versionRow: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "12px 14px",
    marginBottom: 8,
  } satisfies CSSProperties,
  versionHeader: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  versionSummary: { fontSize: 13, fontWeight: 500, flex: 1 } satisfies CSSProperties,
  versionDate: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  versionActions: { display: "flex", gap: 8, marginTop: 8 } satisfies CSSProperties,
} as const;
