import type { CSSProperties } from "react";

export const s = {
  card: (accentColor: string): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${accentColor}`,
    background: "var(--bg-elevated)",
  }),
  headerRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  rule: {
    flex: 1,
    margin: 0,
    fontSize: 14.5,
    fontStyle: "italic",
    fontWeight: 600,
    lineHeight: 1.4,
    color: "var(--text-primary)",
    cursor: "text",
  } satisfies CSSProperties,
  editIconBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
    borderRadius: 5,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  ruleTextarea: {
    width: "100%",
    minHeight: 60,
    fontSize: 13.5,
    lineHeight: 1.5,
    padding: 8,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    resize: "vertical",
  } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8, justifyContent: "flex-end" } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  confidenceLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  } satisfies CSSProperties,
  barWrap: { flex: 1 } satisfies CSSProperties,
  confidencePct: {
    fontSize: 12,
    color: "var(--text-secondary)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  } satisfies CSSProperties,
} as const;
